limit_conn_zone $binary_remote_addr zone=beta65_connections:1m;
server {
    listen 172.252.236.4:27065 ssl;
    ssl_certificate /etc/letsencrypt/live/blocknload.cc/fullchain.pem;
    ssl_certificate_key /etc/letsencrypt/live/blocknload.cc/privkey.pem;
    ssl_protocols TLSv1.2 TLSv1.3;
    ssl_handshake_timeout 10s;
    limit_conn beta65_connections 12;
    proxy_pass 127.0.0.1:27065;
    proxy_connect_timeout 5s;
    proxy_timeout 10m;
}
