using System.Linq.Expressions;
using System.Reflection;
using BNLReloadedServer.BaseTypes;
using BNLReloadedServer.Database;

int checks=0;
void Check(bool pass,string name) { if(!pass)throw new Exception(name);checks++;Console.WriteLine("PASS "+name); }
var constructor=typeof(UnitUpdater).GetConstructors().Single(c=>c.GetParameters().Length==20);
var callbacks=constructor.GetParameters().Select(p=> {
 var invoke=p.ParameterType.GetMethod("Invoke")!;
 return (object)Expression.Lambda(p.ParameterType,Expression.Default(invoke.ReturnType),invoke.GetParameters().Select(a=>Expression.Parameter(a.ParameterType,a.Name))).Compile();
}).ToArray();
var pulses=new List<uint[]>();
var updater=(UnitUpdater)constructor.Invoke(callbacks);
updater=updater with { OnApplyInstEffect=(_,units,_,_,_,_,_,_)=> { pulses.Add(units.Select(u=>u.Id).ToArray()); return true; } };
var catalogue=(ServerCatalogue)Databases.Catalogue;
var hero=new CardUnit { Id="fixture_self_hero",Data=new UnitDataPlayer() };
var friendly=new EffectTargeting { AffectedTeam=RelativeTeamType.Friendly };
var child=new CardEffect { Id="fixture_self_child",Positive=true,Effect=new ConstEffectBuff { Targeting=friendly,Buffs=new() { [BuffType.BuildSpeed]=1 } } };
var wrapper=new CardEffect { Id="fixture_self_wrapper",Effect=new ConstEffectSelf { Targeting=friendly,ConstantEffects=[new Key(child.Id)] } };
catalogue.Replicate([hero,child,wrapper]);
Unit Create(uint id,TeamType team)=>new(id,new UnitInit { Key=hero.Key,Team=team,PlayerId=id,OwnerId=id },updater);
var caster=Create(1,TeamType.Team1);var second=Create(2,TeamType.Team1);var target=Create(3,TeamType.Team2);
var info=new ConstEffectInfo(wrapper.Key);var source=caster.GetSelfSource();
target.AddEffect(info,caster.Team,source);
Check(target.ActiveEffects.Any(e=>e.Key==wrapper.Key) && target.ActiveEffects.Any(e=>e.Key==child.Key),"enemy holder receives self wrapper and friendly nested buff");
Check(caster.ActiveEffects.Count==0,"caster does not receive holder effects");
var sources=(Dictionary<Key,HashSet<EffectSource>>)typeof(Unit).GetField("_effectSources",BindingFlags.Instance|BindingFlags.NonPublic)!.GetValue(target)!;
Check(sources[child.Key].Contains(source),"nested buff retains original caster source for attribution");
target.AddEffects([new ConstEffectInfo(wrapper.Key)],second.Team,second.GetSelfSource());
Check(target.ActiveEffects.Count(e=>e.Key==child.Key)==1 && target.ActiveEffects.Count(e=>e.Key==wrapper.Key)==1,"multiple casters do not duplicate the self wrapper or child");
target.RemoveEffect(info,caster.Team,source);
Check(target.ActiveEffects.Any(e=>e.Key==child.Key),"remaining source keeps shared wrapper active");
target.RemoveEffect(info,second.Team,second.GetSelfSource());
Check(target.ActiveEffects.Count==0,"last source removal cleans up self wrapper and nested buff");
target.AssignFreeForAllTeam(3);caster.AssignFreeForAllTeam(1);
target.AddEffects([new ConstEffectInfo(wrapper.Key)],caster.Team,source);
Check(target.ActiveEffects.Any(e=>e.Key==child.Key),"self nested targeting uses holder identity in FFA");
target.RemoveEffects([info],caster.Team,source);
Check(target.ActiveEffects.Count==0,"FFA cleanup uses the same holder-relative targeting");
target.AddEffects([new ConstEffectInfo(child.Key)],caster.Team,source);
Check(target.ActiveEffects.Count==0,"normal friendly buff still rejects an enemy");
var excluded=new CardEffect { Id="fixture_self_excluded",Effect=new ConstEffectSelf { Targeting=new EffectTargeting { AffectedUnits=[UnitType.Turret] },ConstantEffects=[child.Key] } };
catalogue.Replicate(catalogue.All.Append(excluded).ToList());target.AddEffect(new ConstEffectInfo(excluded.Key),caster.Team,source);
Check(target.ActiveEffects.Count==0,"self still respects recipient unit-type filters");
var interval=new CardEffect { Id="fixture_self_interval",Effect=new ConstEffectSelf { Targeting=friendly,Interval=600,IntervalEffects=[new InstEffectAddResource { Amount=1 }] } };
catalogue.Replicate(catalogue.All.Append(interval).ToList());
target.AddEffect(new ConstEffectInfo(interval.Key),caster.Team,source);
Check(pulses.Count==1 && pulses[0].SequenceEqual(new[]{target.Id}),"self interval pulses target the enemy holder exclusively");
target.AddEffect(new ConstEffectInfo(interval.Key),caster.Team,source);
Check(pulses.Count==1,"duplicate application does not start another interval updater");
var timed=new CardEffect { Id="fixture_self_timed",Duration=10,Effect=new ConstEffectSelf { Targeting=friendly,ConstantEffects=[child.Key] } };
catalogue.Replicate(catalogue.All.Append(timed).ToList());target.AddEffect(new ConstEffectInfo(timed.Key),caster.Team,source);
Check(target.ActiveEffects.Any(e=>e.Key==child.Key),"timed self wrapper applies its child");
target.PurgeEffects(false,true);
Check(!target.ActiveEffects.Any(e=>e.Key==timed.Key || e.Key==child.Key),"purging timed parent removes its permanent child");
Console.WriteLine($"Self effect fixture passed: {checks} checks.");
